# Generated by Django 2.0.7 on 2018-08-11 08:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_areainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tinymceTest1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
