# Generated by Django 2.0.7 on 2018-08-11 09:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_tinymcetest1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinymcetest1',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
